language: node_js
node_js:
  - lts/*
install:
  - npm install
cache:
  directories:
    - "node_modules"
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true 
  local_dir: docs/.vuepress/dist
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  keep-history: true
  fqdn: note.wenboz.com
  on:
    branch: master
